### ISSUE TITLE
(macOS) dylib load error

### ISSUE THREAD

**Issue by DigiEggz** [Vatuu/discord-rpc#5]
After importing the library, when I try to run my app I get the following error:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': dlopen(libdiscord-rpc.dylib, 9): image not found
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:163)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:236)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:379)
	at com.sun.jna.Native.loadLibrary(Native.java:364)
	at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:114)
	at net.arikia.dev.drpc.DiscordRPC.discordInitialize(DiscordRPC.java:33)
	at com.relic.sfs2x.Relic.init(Relic.java:65)
	at com.smartfoxserver.v2.entities.managers.SFSExtensionManager.createExtension(SFSExtensionManager.java:303)
	at com.smartfoxserver.v2.entities.managers.SFSZoneManager.createRoom(SFSZoneManager.java:719)
	at com.smartfoxserver.v2.entities.managers.SFSZoneManager.createZone(SFSZoneManager.java:412)
	at com.smartfoxserver.v2.entities.managers.SFSZoneManager.initializeZones(SFSZoneManager.java:239)
	at com.smartfoxserver.v2.SmartFoxServer.start(SmartFoxServer.java:292)
	at com.smartfoxserver.v2.Main.main(Main.java:14)
`

I'm running 10.13.3 Beta. Is there another way I can include the rpc binaries? Nothing I try seems to behave.

**Comment by bddvlpr** [comment]
Closed the issue but didn't put an answer?
Still looking for an answer.

**Comment by Vatuu** [comment]
@StijnSimons 1. The issue wasn't closed by me, but the author.
2. This issue was related to an outdated version of the library, when you have problems, make sure to use the latest version.

**Comment by bddvlpr** [comment]
@Vatuu I'm using the 1.4.2 version right now on maven, so that shouldn't be a problem.
