### ISSUE TITLE
cant run this in a jar

### ISSUE THREAD

**Issue by Cheese-Berger** [Vatuu/discord-rpc#52]
i cant run this lib in a jar

my code: 
```
        DiscordRichPresence rich = new DiscordRichPresence.Builder("le chungus")
            .setDetails("living in pain")
            .setBigImage("smile", "when the impostor is sus")
            .build();
        DiscordRPC.discordUpdatePresence(rich);
        String appid = "833570157753794561";
        DiscordEventHandlers handlers = new DiscordEventHandlers.Builder().setReadyEventHandler((user) -> {
          System.out.println("hi " + user.username + "#" + user.discriminator + "!");
         }).build();
         DiscordRPC.discordInitialize(appid, handlers, true);

```

error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: net/arikia/dev/drpc/DiscordEventHandlers$Builder
        at me.cheesee.App.main(App.java:102)
Caused by: java.lang.ClassNotFoundException: net.arikia.dev.drpc.DiscordEventHandlers$Builder
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

additional info

 - Java Version: java version "1.8.0_281"
 - Library Version: newest

**Comment by ChickChuck2** [comment]
****it's also happening with me

**Comment by Cheese-Berger** [comment]
> ****it's also happening with me

i figured it out 
are you using maven?

**Comment by ChickChuck2** [comment]
> > ****it's also happening with me
> 
> i figured it out
> are you using maven?

yes, maven

**Comment by byronbonkers** [comment]
I have a very similar problem,``java.lang.NoClassDefFoundError: net/arikia/dev/drpc/callbacks/ReadyCallback
	at Thorn.ThornClient.<init>(ThornClient.java:57)
	at Thorn.ThornClient.<clinit>(ThornClient.java:45)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:461)
	at net.minecraft.client.Minecraft.run(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(Main.java:114)
Caused by: java.lang.ClassNotFoundException: net.arikia.dev.drpc.callbacks.ReadyCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more``
So how do I fix this, pls help me fix it.
